package com.njwd.exception;

/**
 * 结果类型
 *
 * @author CJ
 */
public enum ResultCode {

	/* ============================ 通用错误码 ========================== **/
	/**
	 * 禁止访问 303
	 **/
	PARAMS_NOT(303, "缺少参数"),

	/**
	 * 存在错误参数 304
	 */
	PARAMS_NOT_RIGHT(304, "存在错误参数"),
	DATA_ERROR(305, "存在错误测试数据"),
	/**
	 * 错误请求 400
	 **/
	BAD_REQUEST(400, "错误请求"),

	/**
	 * 未经授权 401
	 **/
	UNAUTHORIZED(401, "未经授权"),

	/**
	 * 禁止访问 403
	 **/
	FORBIDDEN(403, "禁止访问"),
	/**
	 * 连接超时
	 **/
	TIME_OUT(408, "连接超时"),
	/**
	 * Feign连接错误
	 **/
	FEIGN_CONNECT_ERROR(409, "feignClient 连接错误：%s"),
	/**
	 * 操作异常 500
	 **/
	INTERNAL_SERVER_ERROR(500, "操作异常"),

	/**
	 * 操作失败
	 **/
	OPERATION_FAILURE(507, "操作失败"),

	/**
	 * 获取运营平台数据失败
	 */
	PLATFORM_FAILURE(508, "获取运营平台数据失败"),

	/* ============================ 业务/错误码 start========================== **/
	/* ===========================后台系统======================== **/
	RECORD_NOT_EXIST(10001, "相关记录不存在"),
	SYS_USER_INVALID(10002, "用户登录已过期"),
	PERMISSION_NOT(10003, "无访问权限"),
	ACCOUNT_NOT(10004, "账号异常"),
	SHIRO_ERROR(10005, "鉴权/授权过程出错"),
	MENU_EXIST(10006, "菜单定义已存在！"),
	ROLE_EXIST(10007, "角色定义已存在！"),
	CODE_EXIST(10008, "编码已存在！"),
	NAME_EXIST(10009, "名称已存在,不能重复添加!"),
	ROLE_DELETE_HALF(10010, "部分岗位未删除成功！"),
	ROLE_REFER_USER(10011, "岗位已关联用户！"),
	SYS_USER_DISABLE(10012, "该账号已禁用！"),
	USER_ROLE_EXIST(10013, "存在关联的用户权限！"),
	BUSINESS_EXIST(10014, "存在关联的业务单元！"),
	IS_REFERENCE(10015, "当前记录被引用！"),
	USER_NOT_EXIST(10016, "您当前没有权限操作，请联系管理员授权"),
	ACCOUNT_ENTITY_NOT_EXIST(10015, "暂无核算主体！"),
	SIMPLE_NAME_EXIST(10016, "简称已存在！"),
	SOME_SYSTEM_IS_ENABLE(10017, "存在已启用子系统！"),
	ID_IS_NULL(10018, "当前记录ID为null!"),
	CREDIT_CODE_EXIST(10019, "统一社会信用代码已存在!"),
	TAXPAYER_NUMBER_EXIST(10020, "纳税人识别号已存在!"),
	REGISTE_NUMBER_EXIST(10021, "工商注册号已存在!"),
	/* ===========================基础资料======================== **/
	COLUMN_EXIST(11000, "字段有重复！"),
	SUBJECT_CODE_EXIST(11001, "科目编码已存在！"),
	BANK_ACCOUNT_EXIST(11002, "银行账号已存在！"),
	BANK_NAME_EXIST(11003, "账号名称已存在！"),
	IS_DEL(11004, "数据已删除！"),
	IS_ENABLE(11005, "数据已生效！"),
	IS_DISABLE(11006, "数据已失效！"),
	INFO_EXIST(10007, "信息重复！"),
	UNIFIED_SOCIAL_CREDIT_CODE_EXIST(11008, "统一社会信用代码已存在！"),
	ID_CARD_NUM_EXIST(11009, "身份证已存在！"),
	MAX_LEVEL(11010, "当前所选上级部门已为4级部门！"),
	CODING_FORMAT_NO_RIGHT(11011, "编码格式错误！"),
	SEQUENCE_LENGTH_OUT(11012, "当前序列值超过指定长度最大值！"),
	IS_DEL_FAILED(11013, "现金流量模板删除失败!"),
	CITE_DATA_EXIST(11014, "引用数据已存在！"),
	CASH_FLOW_TEMP_IMPORT_FAILED(11015, "现金流量模板导入失败！"),
	IS_CITED(11016, "数据已被引用！"),
	IS_CHANGE(11017, "数据已被修改,请重新刷新页面！"),
	IS_NOT_FINAL(11018, "数据为非末级！"),
	IS_REFERENCED(11019, "部门已被引用，上级部门不能变更！"),
	IS_END_LEVEL(11020, "只能变更末级部门的使用公司及其业务单元，请选择末级部门进行操作！"),
	DEL_NO_END_LEVEL(11021, "删除失败，请先删除下级部门！"),
	PARENT_DEPT_NO_OR_DISABLE(11022, "上级部门不存在，或已禁用！"),
	ATTR_BUSINESS_UNIT_NO(11023, "归属公司业务单元不存在！"),
	BUSINESS_UNIT_NO(11024, "使用公司业务单元不存在！"),
	ACCOUNT_ENTITY_CODE_NOT_EXIST(11025, "核算主体编码对应核算主体不存在!"),
	BANK_NOT_EXIST(11026, "开户银行不存在!"),
    OPERATIONAL_ACCOUNTBOOKENTITY_NOT_EXIST(11027,"未分配可操作的核算主体!"),
	IS_USED_BY_DEPT(11028,"已被部门模块引用"),
	COMPANY_NOT_EXIST_OR_DISABLE(11029, "创建公司编码对应公司不存在，或已禁用！"),
	PARENT_DEPT_IS_DISABLE(11030, "上级部门已失效，请刷新页面！"),
	PARENT_DEPT_IS_USED(11031, "上级部门已使用，无法新增下级！"),
	PARENT_DEPT_IS_DEL(11032, "上级部门已删除，请刷新页面！"),
	DEPT_IS_USED(11033, "当前数据已使用，无法新增下级！"),
	DATA_TYPE_ERROR(11034,"当前资料类型无法升级！"),
	USE_COMPANY_IS_SAME(11035,"当前使用公司与变更公司相同，请刷新数据！"),
	UNIFIED_SOCIAL_CREDIT_CODE_IS_NOT_NULL(11306,"当类型为企业时，统一社会信用代码不能为空"),
	ID_CARD_NUM_IS_NOT_NULL(11307,"当类型为个人时，身份证号码不能为空"),
	USECOMPANY_DATATYPEDISTRIBUTION(11308, "数据类型不是分配型,无法分配!"),
	COMPANY_NAME_NOT_EXIST(11309,"公司对应名称不存在!"),
	NAME_FORMAL_ERROR(11310,"名称不能包含特殊符号和空格!"),
	DEPT_NAME_REPEAT(11311,"表格内存在同一个创建公司内同级部门的名称重复!"),
	DATA_IS_DISTRIBUTE(11312,"数据已被分配"),
	INVAILD_CREDIT_CODE(11313, "统一社会信用代码格式不合法!"),
	ONLY_SHARE_AND_DISTRIBUTION(11314, "集团创建，资料类型只能是共享和分配!"),
	ONLY_PRIVATE(11315, "公司创建，资料类型只能是私有!"),
	NOT_CONFIG(11316,"暂未配置未来期间数!"),
	UPLOAD_BLOC_ERROR(11317,"USER端不能上传集团数据!"),
	DELETE_FAIL_DATA_USED(11318,"当前数据已使用，无法删除"),
	/*========================员工/错误码================================== **/
	COMPANY_ID_NOT_EXIST(11100, "归属公司不能为空!"),
	CODE_NOT_EXIST(11101, "员工编码不能为空!"),
	NAME_NOT_EXIST(11102, "员工姓名不能为空!"),
	DEPT_ID_NOT_EXIST(11103, "部门不能为空!"),
	CONTACT_NUMBER_NOT_EXIST(11104, "手机号不能为空!"),
	CODE_OVER_LENGTH(11105, "自定义员工编码不能超过20个字符!"),
	NAME_OVER_LENGTH(11106, "员工姓名不能超过20个字符!"),
	CONTACT_NUMBER_OVER_LENGTH(11107, "手机号不能超过20个字符!"),
	BANK_ACCOUNT_OVER_LENGTH(11108, "银行号不能超过20个字符!"),
	BANK_ACCOUNT_FAIL(11137, "银行账号格式不正确!"),
	BANK_NAME_FAIL(11138, "账号名称格式不正确!"),
	INVAILD_ID_CARD_NUM(11109, "身份证号格式不合法!"),
	REMARK_OVER_LENGTH(11110, "描述不能超过200个字符!"),
	INVAILD_EMAIL(11111, "邮箱格式不合法!"),
	INVAILD_COMPANY_ID(11112, "公司对应编码不存在!"),
	INVAILD_CONTACT_NUMBER(12000, "手机号格式不合法!"),
	EXIST_CONTACT_NUMBER(12001, "已存在的手机号!"),
	INVAILD_BANK_ACCOUNT(12002, "银行号格式不合法!"),
	EXIST_BANK_ACCOUNT(12003, "已存在的银行号!"),
	STAFF_IS_REFERENCED(12004, "员工已被引用，创建公司、员工编码及员工姓名均不能变更！"),
	COMPANY_NOT_EXIST(12005, "创建公司编码对应公司不存在!"),
	DEPT_NOT_EXIST(12006, "部门编码对应部门不存在!"),
	INVAILD_STAFF_NAME(12007, "员工姓名不符合规则!"),
	INVAILD_ID_CARD_NUMBER(12008, "无效的身份证号!"),
    STAFF_DELETED_OR_DISABLED(12009, "该员工信息已被删除/禁用!"),
    STAFF_DELETED_OR_ENABLED(12010, "该员工信息已被删除/反禁用!"),
    STAFF_INFO_CHANGED(12011, "该员工信息已被他人修改，请刷新后重新修改!"),
	STAFF_DELETED(12012, "该员工信息已被删除!"),
	DEPT_IS_NOT_END(12013,"所选部门非末级，无法引用！"),
	/* ============================ 自定义核算项目/错误码 ============================ **/
	ACCOUNTING_ITEM_CODE_OVER_LENGTH(11113, "自定义核算项目编码不能超过20个字符!"),
	ACCOUNTING_ITEM_NAME_OVER_LENGTH(11114, "自定义核算项目名称不能超过20个字符!"),
	ACCOUNTING_ITEM_USECOMPANY_NOEXIST(11142, "自定义核算项目使用公司不存在!"),
	ACCOUNTING_ITEM_COMPANY_NOEXIST(11143, "自定义核算项目归属公司不存在!"),
	ACCOUNTING_ITEM_NOEXIST(11144, "自定义核算项目不存在!"),
	ACCOUNTING_ITEM_ISDEL(11145, "自定义核算项目已经被删除!"),
	ACCOUNTING_ITEM_ISENABLE(11146, "自定义核算项目已经被反禁用!"),
	ACCOUNTING_ITEM_VALUE_ISDEL(11147, "自定义核算项目大区值已经被删除!"),
	ACCOUNTING_ITEM_VALUE_ISENABLE(11148, "自定义核算项目大区值已经被反禁用!"),
	ACCOUNTING_ITEM_ISDISENABLE(11149, "自定义核算项目已经被禁用!"),
	ACCOUNTING_ITEM_VALUE_ISDISENABLE(11150, "自定义核算项目大区值已经被禁用!"),
	ACCOUNTING_ITEM_VALUE_EXIST(11170, "删除将会连带值列表中的值一起删除!"),
	ACCOUNTING_ITEM_ISRELA_SUBJECT(11171, "自定义核算项目已经被科目表引用,不能被删除!"),
	/* ============================ 会计科目操作/错误码 ============================ **/
	ACCOUNT_SUBJECT_CODE_OVER_LENGTH(11115, "科目编码超过最大长度限制!"),
	UP_ACCOUNT_SUBJECT_NOT_EXIST(11116, "上级科目不存在!"),
	ACCOUNT_CATEGORY_NOT_EXIST(11117, "分类不存在!"),
	CASH_INFLOW_NOT_EXIST(11118, "现金流入项目不存在!"),
	CASH_INFLOW_WRONG_DIRECTION(11119, "现金流入项目方向不是现金流入!"),
	CASH_OUTFLOW_NOT_EXIST(11120, "现金流出项目不存在!"),
	CASH_OUTFLOW_WRONG_DIRECTION(11121, "现金流出项目方向不是现金流出!"),
	AUXILIARY_NOT_EXIST(11122, "辅助核算项目不存在!"),
	UP_CODE_ONE_TO_MANY(11123, "上级科目编码对应多条数据!"),
	CODE_AND_UP_CODE_RULE_WRONG(11124, "科目编码与上级科目编码关系有误!"),
	SUBJECT_NAME_EXIST(11125, "科目名称已存在！"),
	ACCOUNT_CATEGORY_ONE_TO_MANY(11126, "分类对应多条数据!"),
	CASH_INFLOW_ONE_TO_MANY(11127, "现金流入对应多条数据!"),
	CASH_OUTFLOW_ONE_TO_MANY(11128, "现金流出对应多条数据!"),
	AUXILIARY_ONE_TO_MANY(11129, "辅助核算项目对应多条数据!"),
	ADD_UNDER_INIT_DATA(11130, "该预置科目下不能新增下级数据!"),
	CURRENCY_DELETE(11131, "删除会计科目与币种关系信息失败!"),
	AUXILIARY_DELETE(11132, "删除会计科目与辅助核算关系信息失败!"),
	UP_ACCOUNT_SUBJECT_DISABLE(11133, "上级科目已禁用!"),
	SUBJECT_NOT_EXIST(11134, "科目表不存在!"),
	COULD_NOT_CANCEL_ENABLE(11135, "已被会计科目使用，无法取消启用!"),
	WRONG_CODE(11136, "科目编码不能以00结尾!"),
	/* ============================ 基础资料.项目/错误码 end============================ **/
	PROJECT_NAME_EXIST(11200, "项目名称已存在!"),
	PROJECT_NAME_OVER_LENGTH(11201, "项目名称长度不能超过50个字符!"),
	PROJECT_NAME_ISEMPTY(11202, "项目名称不能为空!"),
	PROJECT_CODE_ISEMPTY(11203, "项目编码不能为空!"),
	PROJECT_COMPANY_ISEMPTY(11204, "项目归属公司不能为空!"),
	PROJECT_COMPANY_NOEXIST(11205, "项目归属公司不存在!"),
	PROJECT_COMPANY_USESHIRO(11224,"无当前创建公司使用权限!"),
	PROJECT_CODE_SYSCODERRROR(11205, "系统编码生成错误!"),
	PROJECT_USECOMPANY_NOEXIST(11206, "项目使用公司不存在!"),
	PROJECT_USECOMPANY_ISEMPTY(11214, "项目使用公司不能为空!"),
	PROJECT_DEPARTMENT_ISEMPTYY(11207, "项目负责部门不能为空!"),
	PROJECT_DEPARTMENT_NOEXIST(11208, "项目负责部门不存在!"),
	PROJECT_ISDELTE_HASDELETE(11209, "项目已被删除!"),
	PROJECT_ISENABLE_HASENABLE(11210, "项目已被启用!"),
	PROJECT_ISENABLE_HASDISABLE(11211, "项目已被禁用!"),
	PROJECT_PERSONINCHARG_NOEXIST(11212, "项目负责人不存在!"),
	PROJECT_ISPHONENUM_NOTPHONE(11213, "手机号码格式不对!"),
	PROJECT_USECOMPANY_DATATYPEDISTRIBUTION(11214, "数据类型不是分配型,无法分配项目!"),
	PROJECT_USECOMPANY_DATATYPEPRIVATE(11215, "仅私有型可变更资料类型,且只可变更为分配型!"),
	PROJECT_USECOMPANY_DATATYPEADMIN(11216, "创建公司为集团时,资料类型仅可为共享型或分配型!"),
	PROJECT_USECOMPANY_DATATYPEUSER(11217, "创建公司为非集团时,资料类型仅可为私有型!"),
	PROJECT_USECOMPANY_DATAUSEDERROR(11218, "项目已被使用,无法进行操作!"),
	PROJECT_ADD_PROJECTINFOBYADMIN(11219,"控制策略无法创建集团数据!"),
	PROJECT_ADD_PROJECTINFOBYSHARE(11220,"控制策略无法创建共享型数据!"),
	PROJECT_ADD_PROJECTINFOBYDISTRIBUTION(11221,"控制策略无法创建共享型数据!"),
	PROJECT_ADD_PROJECTINFOBYPRIVATE(11222,"控制策略无法创建共享型数据!"),
	PROJECT_USECOMPANY_DATATYPEPRIVATEOTHER(11223, "限制变更资料类型!"),
	PROJECT_DELETE_DELETEPROJECTUSED(11224,"当前项目已被其他公司使用，无法删除!"),
	CUSTOMER_SUPPLIER_PLATFORM_FAIL(11174, "连接客户供应商平台失败!"),
	/* ============================ 基础资料.现金流量项目/错误码 end============================ **/
	CASH_FLOW_ITEM_HASDEL(11151, "数据已被删除！"),
	CASH_FLOW_ITEM_DEL_FAILED(11152, "现金流量项目删除异常！"),
	CASH_FLOW_ITEM_NO_DATA(11153, "平台无数据返回！"),
	CASH_FLOW_ITEM_MAX_LEVEL(11154, "超过最大级次！"),
	CASH_FLOW_ITEM_CODE_EXIST(11155, "【科目编码】已存在，不能重复增加！"),
	CASH_FLOW_ITEM_NAME_EXIST(11156, "【科目名称】已存在，不能重复增加！"),
	CASH_FLOW_ITEM_UP_NOT_EXIST(11157, "现金流量上级项目不存在！"),
	CASH_FLOW_ITEM_UP_CODE_NOT_MATCH_DOWN(11158, "现金流量上下级编码不匹配！"),
	CASH_FLOW_ITEM_IS_CITED(11159, "当前数据已使用无法新增下级！"),
	GROUP_DATA_RULE(11160, "集团数据，USER无权操作！"),
	CASH_FLOW_ITEM_IS_DISABLE(11161, "数据已被禁用！"),
	CASH_FLOW_ITEM_IS_FINAL(11162, "删除失败，请先删除下级项目！"),
	CASH_FLOW_ITEM_IS_INIT_AND_NOT_FINAL(11163, "预置数据上级禁止新增！"),
	CASH_FLOW_ITEM_IS_INIT_DISABLE_DEL(11164, "系统预置项目不可删除！"),
	CASH_FLOW_ITEM_IS_EXIST_INTERIOR(11165, "操作失败，存在内部数据！"),
	CASH_FLOW_ITEM_IS_FINAL_INTERIOR_INIT(11166, "系统预置的末级内部往来项目禁止操作！"),
	CASH_FLOW_ITEM_IS_INIT(11167, "预置数据禁止更新！"),
	CASH_FLOW_ITEM_NO_DATA_EXPORT(11168,"无导出数据"),
	EXIST_INTERIOR_FORBID_ENABLE(11169, "内部往来项目不能反禁用！"),
	EXIST_INTERIOR_FORBID_DISABLE(11170,"内部往来项目不能禁用!"),
	EXIST_DOWN_INTERIOR_OR_IS_INTERIOR(11171,"内部往来或下级存在内部往来数据!"),
	CASH_FLOW_ITEM_CHECK_VERSION(11172,"版本号不一致!"),
	CASH_FLOW_ITEM_CHECK_CODE(11173,"编码不能以00结尾!"),
	CASH_FLOW_ITEM_IS_CITED_FORBID_UPDATE(11174, "被引用数据禁止更新！"),
	CASH_FLOW_NOT_EXIST(11175, "此会计准则下未引入现金流量项目！"),
	CASH_INFLOW_CODE_NAME_NOT_MATCH(11176, "现金流入编码和名称不匹配！"),
	CASH_OUTFLOW_CODE_NAME_NOT_MATCH(11177, "现金流出编码和名称不匹配！"),
	/* ============================ 业务/错误码 end============================ **/
	/* ============================ 总账参数设置/运营平台配置/错误码 start============================ **/
	SAVE_FAILED(20010, "保存失败"),
	PARAMETER_SET_INIT_FAIL(20011, "总账参数初始化失败"),
	PARAMETER_SET_ADMIN_DELETE_FAIL(20012, "租户总账参数无法删除"),
	CREDENTIAL_WORD_TYPE_DELETE_FAIL(20013, "个性化中,已存表账簿设置不允许删除"),
	ACCOUNT_SUBJECT_IS_LAST(20014, "不能为非末级科目"),
	ACCOUNT_SUBJECT_IS_DELETE(20015, "已删除或禁用"),
	PARAMETER_SET_SUBJECT_NOT_EXIST(20016, "参数设置科目表不存在"),
	VOUCHER_EXIST_RIGHT(20016, "参数设置未初始化"),
	MULTI_COLUMN_SCHEME_ITEM(20018, "[多栏账方案明细]栏目不允许重复！"),
	CAN_NOT_SETTLE(20019, "上期未结账，请先结上期！"),
	CAN_NOT_CANCEL_SETTLE(20020, "下期已结账，请先反结下期！"),
	NOT_SETTLE(20021, "本期已结账！"),
	NOT_CANCEL_SETTLE(20022, "本期未结账！"),
	EXIST_VOUCHER_ADMIN(20023, "已存在凭证，无法修改，请对账簿进行设置"),
	EXIST_VOUCHER_ACCOUNT_BOOK(20024, "已存在凭证，无法修改"),
	SYNERGY_ACCOUNT_SUBJECT_ID_USED(20025,"会计科目ID已被使用！"),
	SYNERGY_ACCOUNT_SUBJECT_ID_ERROR(20026, "所选的会计科目与平台配置项不符！"),
	SYNERGY_ACCOUNT_SUBJECT_ONLY_FIRST(20027,"仅能设置一级会计科目！"),
	SYNERGY_ACCOUNT_SUBJECT_APPROVED(20028,"科目协同关系已审核，不可编辑！"),
	SYNERGY_ACCOUNT_SUBJECT_SELECTED_ERROR(20029,"所选的配置与平台配置项不符！"),
	SYNERGY_ACCOUNT_SUBJECT_SELECTED_SAME(20030,"所选的两个科目不能相同！"),
	SYNERGY_ACCOUNT_SUBJECT_AUXILIARY_ERROR(20031,"所选的辅助核算项与平台配置不符！"),
	/* ============================ 总账参数设置/错误码 end============================ **/
	/* ============================ 文件处理 错误码 ========================== **/
	FILE_NOT_EXISTS(20001, "文件不存在"),
	FILE_MUST_IS_EXCEL(20002, "文件类型必须是excel"),
	UPLOAD_EXCEPTION(20003, "上传过程出现异常"),
	EXCEL_RULE_NOT_EXISTS(20004, "excel校验规则不存在"),
	EXCEL_TEMPLATE_NOT_EXISTS(20005, "excel模板不存在"),
	EXCEL_TEMPLATE_NOT_CORRECT(20009, "excel模板不对，请重新下载"),
	EXCEL_DATA_NOT_EXISTS(20006, "excle数据不存在"),
	EXCEL_NOT_CORRECT(20007, "excel不正确"),
	EXCEL_PARSE_CORRECT(20010,"excel解析错误"),
	CURRENT_MONTH_NOT_EXISTS(20008, "当前年月数据不存在"),
	BATCH_NOT_NEED(20009, "无需批量操作！"),

	/* ============================ 总账 ========================== **/
	ACCOUNT_BOOK_LOCK(30001, "凭证期间已锁定（锁定原因：凭证整理或过账或结账操作中），请稍后再%s！"),
	VERSION_ERROR(30002, "该数据已被他人修改！请确认数据后再试！"),
	ONLY_DRAFT(30003, "当前凭证状态不可暂存！"),
	VOUCHER_OPER_EXIST(30004, "当前账簿期间正在操作凭证，请稍候再试！"),
	ACCOUNT_PERIOD_OFF(30005, "期间未打开不允许录入凭证，请检查！"),
	ACCOUNT_PERIOD_SETTLE(30006, "会计期间已结账！"),
	ACCOUNT_SUBJECT_NOT_EXIST(30007, "分录选择的会计科目不存在！"),
	ACCOUNT_SUBJECT_NOT_FINAL(30008, "分录仅可选择末级科目！"),
	CASH_FLOW_ITEM_NOT_EXIST(30009, "现金流量分析选择的现金流量项目不存在！"),
	CASH_FLOW_ITEM_NOT_FINAL(30010, "现金流量分析选择的现金流量项目非末级！"),
	VOUCHER_DATE_ERROR(30011, "制单日期与会计期间不符！"),
	CREDENTIAL_WORD_ERROR(30012, "凭证字与总账设置不一致！"),
	NOT_ALLOW_EDIT_OTHER_VOUCHER(30013, "不允许修改他人凭证！"),
	CHRONOLOGICAL_CONTROL_NEW(30014, "序时控制，制单日期必须大于等于%s日！"),
	IMBALANCE(30015, "借贷不平衡！"),
	NOT_ALLOW_SAVE(30016, "当前凭证状态不可修改！"),
	ACCOUNT_SUBJECT_DISABLE(30017, "分录选择的科目已禁用！"),
	AUXILIARY_ERROR(30018, "分录选择的辅助核算项与科目不符！"),
	EXISTS_NOT_AUDITED_VOUCHER(30019, "存在未审核凭证！"),
	EXISTS_NOT_REVIEWED_VOUCHER(30020, "存在未复核凭证！"),
	SYSTEM_ALREADY_INITLIZED(30021, "子系统已初始化！"),
	SYSTEM_ALREADY_ANTIINITLIZED(30022, "子系统已反初始化！"),
	INTERIOR_ONLY_ONE_SIDE(30023, "内部往来科目只允许出现在一方！"),
	INTERIOR_ERROR(30024, "内部往来明细未录入！"),
	CASH_FLOW_PARAM_ERROR(30025, "现金流量分析明细参数错误！"),
	CASH_FLOW_ANALYZE_IMBALANCE(30026, "现金流量分析不平！"),
	AUXILIARY_ITEM_NOT_EXIST(30027, "分录选择的辅助核算项不存在！"),
	AUXILIARY_ITEM_NOT_ENABLE(30028, "分录选择的辅助核算项已禁用！"),
	SUBJECT_ANALYZE_IMBALANCE(30029, "科目试算平衡不平！"),
	INTERIOR_IMBALANCE(30030, "协同分录借贷不平衡！"),
	INTERIOR_SUBJECT_MISSING_IN_CONFIG(30031, "内部往来科目未配置现金流量默认流入方！"),
	INTERIOR_SUBJECT_MISSING_OUT_CONFIG(30032, "内部往来科目未配置现金流量默认流出方！"),
	INTERIOR_NOT_DELETE(30033, "协同凭证不能直接被删除！"),
	APPROVE_EXIST_CANT_DELETE(30034, "凭证已审核，不允许删除！"),
	REVIEW_EXIST_CANT_DELETE(30035, "凭证已出纳审核，不允许删除！"),
	FORWARD_CANT_DELETE(30036, "损益结转凭证不能直接被删除！"),
	RUSH_CANT_DELETE(30037, "冲销凭证不能删除！"),
	BUSINESS_SYSTEM_CANT_DELETE(30038, "业务系统凭证不能直接被删除！"),
	CASH_FLOW_NEEDLESS(30039, "当前凭证无需进行现金流量分析！"),
	CASH_FLOW_OFF(30040, "现金流量未启用！"),
	SETTLE_CASH_FLOW_CANT_EDIT(30041, "结账后不允许修改现金流量！"),
	NOT_SUPPORT_DRAFT(30042, "该功能不支持暂存凭证！"),
	RUSH_CANT_SAVE_CASH_FLOW(30043, "冲销凭证不能进行现金流量分析！"),
	VOUCHER_NOT_POST(30044, "凭证未过账！"),
	VOUCHER_RUSHED(30045, "凭证已冲销！"),
	VOUCHER_NOT_MANUAL(30046, "非手工凭证！"),
	RUSH_FAIL_REASON_DISABLE(30047, "冲销凭证生成失败，失败原因：%s%s已禁用！"),
	RUSH_DATE_EARLY(30048, "协同凭证生成日期不能早于被冲销凭证日期！"),
	AUXILIARY_ITEM_LIST_NOT_EXIST(30049, "科目期初查询辅助核算信息不存在！"),
	CHRONOLOGICAL_CONTROL_UPDATE(30050, "序时控制，制单日期必须大于等于%s日且小于等于%s！"),
	COMMON_ABSTRACT_CONTENT_EXIST(30051, "[摘要内容]名称重复"),
	CASH_FLOW_OPPOSITE_NOT_EXIST(30052, "现金流量分析所选择的对方分录不存在！"),
	PARENT_VERSION_ERROR(30053, "所属上级已被他人修改！请确认数据后再试！"),
	PARAMETER_SET_NOT_EXIST(30054, "总账参数未设置！"),
	CARRY_SUBJECT_NOT_EXIST(30055, "损益结转选择的会计科目不存在！"),
	CARRY_SUBJECT_NOT_FINAL(30056, "损益结转仅可选择末级科目！"),
	COMMON_ABSTRACT_NO_ROLE_DELETE(30057, "[摘要内容]用户无权限删除集团共享常用摘要"),
	VOUCHER_DATA_NOT_ACCORD_CASH_FLOW(30058, "现金流量分析数据与凭证不一致"),
	ENTRY_ENTITY_SAME_VOUCHER(30059, "凭证核算主体与内部往来科目分录核算主体重复，请检查！"),
	SETTLE_NOT_FINAL(30060, "本年利润科目和利润分配科目必须为非末级科目！"),
	ACCOUNT_PERIOD_NOT_SETTLE(30061, "会计期间未结账，无需反结账！"),
	SETTLE_ERROR(30062, "结账异常，请尝试重新结账，如仍无法结账，请联系管理员处理！"),
	CANCEL_SETTLE_ERROR(30063, "反结账异常，请尝试重新反结账，如仍无法反结账，请联系管理员处理！"),
	SETTLE_PERIOD_ERROR(30064, "%s年第%s期未结账，%s年第%s期不可结账"),
	CANCEL_SETTLE_PERIOD_ERROR(30065, "%s年第%s期已结账，%s年第%s期不可反结账"),
	BALANCE_INIT_RECORD_EXIST(30066, "期初新增核算主体已存在！"),
	BALANCE_INIT_RECORD_DELETED(30067, "当前页面核算主体已被删除！"),
	BALANCE_INIT_RECORD_INIT(30068, "帐簿已初始化不能操作！"),
	BALANCE_INIT_ERROR(30069, "初始化异常，请尝试重新初始化，如仍无法初始化，请联系管理员处理！"),
	BALANCE_DIS_INIT_ERROR(30070, "反始化异常，请尝试重新反始化，如仍无法反始化，请联系管理员处理！"),
	BALANCE_IGNORE(30071, "已忽略，该账簿不需初始化或反初始化！"),
	ACC_SUBJECT_UP_ERROR(30072, "仅可使用当前会计科目表中已审核状态未发布状态的会计科目作为上级！"),
	BASE_ACC_SUBJECT_UP_ERROR(30073, "仅可使用基准表会计科目中的末级会计科目作为上级！"),
	SUBJECT_CATEGORY_NOT_APPROVED(30074, "科目类别未审核！"),
	ACC_SUBJECT_IS_NOT_FINAL(30075, "删除失败，请先删除下级会计科目！"),
	REVERSAL_APPROVE_IS_NOT_FINAL(30076, "存在下级科目，不能反审核！"),


	/* ============================ 财务报告 ========================== **/
	/* ============================ 利润表 ========================== **/
	PROFITSTATEMENT_GROWDATE_ERROR(31001, "利润表增长率必须包含同比值或环比值!"),
	EXPORTDATATOEXCEL_FAIL(31002,"Excel导出失败!"),
	/* ============================ 总账 过账 ========================== **/
	TRANSFER_CALC_BALANCE_ERROR(32001, "过账计算执行过程异常！"),
	FORBID_CANCEL_SETTLE(32002, "“参数选项-允许反结账”未勾选，不允许进行反结账操作"),
	NOT_SETTLE_CONDITION(32003, "结账校验不通过！"),
	/* ============================ 查询方案 ========================== **/
	QUERY_SCHEME_MAX_COUNT(40001,"超出自定义查询方案上限20个"),

	/* ============================ 运营平台 ========================== **/
	IS_APPROVED(50001,"数据已审核"),
	IS_UNAPPROVED(50002,"数据未审核"),
	IS_RELEASED(50003,"数据已发布"),
	DEL_CHECK_APPROVED(50004,"删除失败！无法删除已审核的数据"),
	APPROVE_CHECK_APPROVED(50005,"审核失败！数据已审核，无需重复审核！"),
	DISAPPROVE_CHECK_RELEASED(50006,"反审核失败！数据已发布，无法反审核！"),
	DISAPPROVE_CHECK_DISAPPROVED(50007,"反审核失败！数据未审核，无需反审核！"),
	RELEASE_CHECK_NO_APPROVED(50008,"发布失败！只能发布已审核的数据"),
	RELEASE_CHECK_RELEASED(50009,"发布失败！数据已发布，无需重复发布"),
	STANDARD_UNAPPROVED(50010, "会计准则未审核！"),
	ACC_ELEMENT_UNAPPROVED(50011, "会计要素未审核！"),
	MAXIMUM_LEVEL_ERROR(50012, "最大级次最小为3，最大为6！"),
	STANDARD_BASE_TABLE_EXIST(50013, "每个会计准则只有一个基准表！"),
	BASE_TABLE_NOT_RELEASED(50014, "基准表只能选择已发布的会计科目表！"),
	ALLOW_SELECTED_RELEASED_AUXILIARY(50015, "只能选择已发布的辅助核算项目！"),
	CASH_FLOW_ITEM_CHECK_CODE_FIRST(50016,"第一级编码为1位，且首位不能为0"),
	CASH_FLOW_ITEM_CHECK_FINAL(50017,"删除失败，请先删除下级现金流量项目"),
	CASH_FLOW_ITEM_CHECK_DISAPPROVED(50018,"所选的现金流量项目的所有的上下级项目中存在未审核的现金流量项目，请先审核完成再发布"),
	TAX_SYSTEM_NOT_EXISTS(50019,"税收制度不存在！"),
	TAX_CATEGORY_NOT_EXISTS(50020,"税种不存在！"),
	ACCOUNT_ALREADY_EXIST(50021,"用户名已存在！"),
	MOBILE_ALREADY_EXIST(50022,"手机号已存在！"),
    ENCRYPT_FAILED(50023,"数据加密失败！"),
	REPORT_ITEM_NAME_EXIST(50024, "相同报表类型内，名称不可重复"),
	SUBJECT_AUXILIARY_SELECTED_OVERMUCH(50025, "一个会计科目表最多启用50个核算项目！"),
	BASE_SUBJECT_NOT_RELEASED(50026, "发布失败！所属基准表尚未发布，请先发布所属基准表！"),
	REPROT_ITEM_SET_NOT_EXIST(50027, "审核失败！财务报表无报表项目，无法审核！"),
	UPDATE_USER_FAIL(50028,"调用 Core 接口，修改用户失败！"),
	USER_EXIT(50029,"用户在本组织已存在，无需创建！"),
	USER_EXIT_PULL(50030,"用户账号已注册，请确认信息，是否将其添加至本企业？"),
    ADD_USER_FAIL(50031,"新增用户失败！"),
	AREA_IS_UNAPPROVED(50032,"国家地区未审核！"),
	CURRENCY_IS_UNRELEASED(50033,"币种未发布！"),
	TAX_SYSTEM_IS_UNAPPROVED(50034,"税收制度未审核！"),
	TAX_CATEGORY_IS_UNRELEASED(50035,"税种未发布！"),
	ACC_SUBJECT_CODE_ERROR(50036,"编码与科目表不符！"),
	ACC_SUBJECT_CODE_NOT_ALLOW(50037,"编码不允许使用！"),
	AUXILIARY_SIZE_ERROR(50038,"一个会计科目最多使用10个核算项目！"),
	AUXILIARY_DISABLE(50039,"核算项目未启用！"),
	AUXILIARY_MUTUAL_EXCLUSION(50040,"值来源为“基础资料.客户”和“基础资料.供应商”的项目不能再同一个会计科目的辅助核算中同时使用，属于互斥项目！"),
	ABSTRACT_CONTENT_EXISTS(50041, "摘要内容重复"),
	ABSTRACT_CODE_EXISTS(50042, "助记码重复"),
	ACC_SUBJECT_NO_APPROVED(50043,"所选的会计科目的所有的上下级科目中存在未审核的会计科目，请先审核完成再发布！"),

	FIND_ENTERPRISE_LIST_FAIL(50044,"调用 Core 接口，查询租户列表失败！"),
	NEEDLESS_INTRODUCTION(50045,"只有非基准表才需要引入会计科目！"),
	ACC_SUBJECT_UNRELEASED(50046, "会计科目未发布！"),
	INTRODUCTION_ACC_SUBJECT_CANT_REVERSAL_APPROVE(50047, "引入的基准表科目不能反审核！"),
	DEL_USERS_FAIL(50048,"调用 Core 接口，批量删除用户失败！"),
	CURRENCY_SELECT_ERROR(50049, "非基准表的会计科目使用的核算币种必须大于等于基准表科目的末级科目的核算币种！"),
	AUXILIARY_SELECT_ERROR(50050, "非基准表的核算项目必须大于等于所属基准表的核算项目！"),
	ACC_SUBJECT_EXIST(50051, "会计科目已存在！"),
	MAXIMUM_LEVEL_LESS_BASE(50052, "非基准表的最大级次必须大于等于基准表的最大级次！"),
	REPORT_ITEM_CODE_EXIST(50053, "相同报表类型内，排序不可重复"),
	CASH_FLOW_EXIST(50054, "每个会计准则只有一个现金流量项目表！"),
	ACCOUNT_OR_PASSWORD_NOEXIST(50055,"用户名或密码错误！"),
	DATA_UN_APPROVED(50055,"选择的数据未审核，请重新选择！"),
	DELETE_FAIL(50056,"删除失败！数据已删除"),
	CASH_FLOW_ITEM_CHECK_FINAL_DISAPPROVE(50057,"存在下级项目，不能反审核"),
	FIND_USER_LIST_FAIL(50058,"调用 Core 接口，查询用户列表失败！"),
	SOURCE_EXIST(60000,"相同值来源的核算项目已存在，不能重复增加");
	;
	public final int code;
	public String message;

	ResultCode(int code, String message) {
		this.code = code;
		this.message = message;
	}

	public int getCode() {
		return code;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
}
