# server配置
server:
  port: 8186
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /ledger

# spring配置
spring:
  profiles:
    active: test
  application:
    name: ledger
  cloud:
    nacos:
      config:
        server-addr: 118.31.126.55:8848
        file-extension: yaml
      #        namespace:
      discovery:
        server-addr: 118.31.126.55:8848
        enabled: true
        namespace : libao
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp128726c51f24v7plo.mysql.rds.aliyuncs.com:3306/njwd_finance_ledger?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: cw_admin
    password: jsbgsn123456!
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 8
    tomcat:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT1FROMDUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    database: 4
    host: 118.31.126.55
    port: 6379
    password: sys1234
    # 使用连接池
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        min-idle: 0
  rabbitmq:
    host: 118.31.126.55
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8
    serialization:
      # 不使用时间戳
      write-dates-as-timestamps: true
ribbon:
  ReadTimeout: 120000
  #请求连接的超时时间
  ConnectTimeout: 30000
logging:
  config: classpath:logback-dev.xml

mybatis-plus:
  mapper-locations: classpath*:/com/njwd/**/mapper/xml/*.xml
  typeAliasesPackage: com.njwd.*.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      table-prefix: wd_
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-handlers-package: com.njwd.handler
system:
  properties:
    profileActive: test
    njwdCoreUrl: 'http://47.111.176.87:8188/njwd_core/'

#自定义常量
constant:
  file:
    #服务端excel的保存路径,模版在该路径下,上传的excle文件在对应文件夹下
    excelRootPath: /home/njwd_finance_back/excel_upload/
