# server配置
server:
  port: 8185
  tomcat:
    uri-encoding: UTF-8

# spring配置
spring:
  application:
    name: async-server
  profiles:
    active: pre
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp18r56pt0hp3k88k.mysql.rds.aliyuncs.com:3306/njwd_finance_back_sys?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: cw_admin
    password: sys8888!
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 8
    tomcat:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT1FROMDUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    database: 5
    host: 172.16.0.21
    port: 6379
    password: sys1234
      # 使用连接池
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        min-idle: 0
  rabbitmq:
    host: 172.16.0.21
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8
    serialization:
      # 不使用时间戳
      write-dates-as-timestamps: true
  cloud:
    nacos:
      config:
        server-addr: 118.31.126.55:8848
        file-extension: yaml
      #        namespace:
      discovery:
        server-addr: 118.31.126.55:8848
        enabled: true
      #  namespace: pre

logging:
  config: classpath:logback.xml

mybatis-plus:
  mapper-locations: classpath*:/com/njwd/**/mapper/xml/*.xml
  typeAliasesPackage: com.njwd.*.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      table-prefix: wd_
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

system:
  properties:
    profileActive: pre
    njwdCoreUrl: 'http://172.16.0.18:8188/njwd_core/'

#自定义常量
constant:
  file:
    #服务端excel的保存路径,模版在该路径下,上传的excle文件在对应文件夹下
    excelRootPath: /home/njwd_finance_back/excel_upload/
